/*
 * (c) Copyright 2016 G. Campana
 * (c) Copyright 2016 Quarkslab
 *
 * This file is part of Cappsule.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef CUAPI_ERROR_H
#define CUAPI_ERROR_H

#define CAPPSULE_ERRNO_BASE	256

enum hv_error {
	HV_SUCCESS = 0,

	/* hypervisor initialisation */
	ERROR_ALLOC_GUARD_PAGE,
	ERROR_ALLOC_FAILED,
	ERROR_LOG_DEVICE_REGISTRATION,
	ERROR_SYMBOL_RESOLUTION,
	ERROR_CHECK_BREAKPOINTS,
	ERROR_XCHAN_INTR_VECTOR,
	ERROR_MFN_DEVICE_REGISTRATION,
	ERROR_SHRINK_MEMORY,
	ERROR_VMX_ALREADY_ENABLED,
	ERROR_VMLAUNCH_FAILED,
	ERROR_VMXON_FAILED,
	ERROR_CPU_FORK,
	ERROR_CPU_NO_VMX,
	ERROR_CPU_NO_SECONDARY_CONTROLS,
	ERROR_CPU_NO_EPT,
	ERROR_CPU_VMX_DISABLED,
	ERROR_CPU_WB_MEMORY_TYPE,
	ERROR_CPU_NO_INVEPT,
	ERROR_CPU_INVEPT_SINGLE_CONTEXT,
	ERROR_CPU_INVEPT_TYPE,
	ERROR_CLEAR_TRUSTED_VMCS,
	ERROR_LOAD_TRUSTED_VMCS,
	ERROR_CLEAR_CAPSULE_VMCS,
	ERROR_LOAD_CAPSULE_VMCS,

	/* snapshot */
	ERROR_SNAP_ALREADY_DONE,
	ERROR_SNAP_MODULE_BEING_REMOVED,
	ERROR_SNAP_PARAMS_NPAGES_TOO_LARGE,
	ERROR_SNAP_CPUS_ONLINE,
	ERROR_SNAP_FIX_SET_HOOK,
	ERROR_SNAP_FIX_INVALID_ADDR,
	ERROR_SNAP_FIX_MULTIPLE_PAGES,
	ERROR_SNAP_ERASE_MODULE_MEMORY,
	ERROR_SNAP_ARGV_GPA,

	ERROR_SNAP_PID_BITMAP_ALLOC_FAILED,
	ERROR_SNAP_SET_PFN_ALLOC_FAILED,
	ERROR_SNAP_ALLOC_COPY_PAGES,
	ERROR_SNAP_COUNT_DATA_PAGES,
	ERROR_SNAP_CREATE_SNAP_ALLOC_FAILED,
	ERROR_SNAP_INVALID_PTE,
	ERROR_SNAP_PTE_LEVEL_SET,

	/* capsule creation */
	ERROR_CREATION_NO_SNAPSHOT,
	ERROR_CREATION_MODULE_BEING_REMOVED,
	ERROR_CREATION_MAX_CAPSULE,
	ERROR_CREATION_ALLOC_FAILED,
	ERROR_CREATION_INVALID_USER_PAGES,
	ERROR_CREATION_XCHAN_ALLOC_FAILED,
	ERROR_CREATION_KTHREAD_FAILED,

	/* xchan */
	ERROR_XCHAN_DEVICE_REGISTRATION,

	HV_ERROR_MAX
};

#endif /* CUAPI_ERROR_H */
